### ISSUE TITLE
Error when run it in python

### ISSUE THREAD

**Issue by vlaha5** [SUP3RIA/Atlantr#24]
Always getting same error when running it in python

File "atr3.py", line 246
    print "\n[INFO]Shutting down gracefully (takes a while)"

[https://imgur.com/YqyVElz
](url)
Just copy link of image and open it in new tab

**Comment by ghost** [comment]
Check your python version! I think you were using python 3 use python 2.7

**Comment by filebe777** [comment]
same issues bro ---

python atr3.py -i mailpass.txt -o output.txt -t 100 -g true 
  File "atr3.py", line 246
    print "\n[INFO]Shutting down gracefully (takes a while)"
          ^
SyntaxError: invalid syntax

**Comment by ghost** [comment]
Please confirm your python version by typing python --version if you have installed python 3 before and then installing python 2 then change your environment path or you can just copy atr3.py to the C:\Python27 directory.

**Comment by filebe777** [comment]
python --version
Python 3.8.3
On the latest Kali linux - #uname -v
#1 SMP Debian 5.6.14-1kali1 (2020-05-25)

**Comment by p0isonBR** [comment]
run $ python2 atr3.py -i mailpass.txt -o output.txt -t 100 -g true
if you not have python2, use $ pip install python2

**Comment by filebe777** [comment]
same thing
[~/Desktop/Atlantr/3.0]
└──╼ #python2 atr3.py -i 296k.txt -o output.txt -t 100 -g true
Traceback (most recent call last):
  File "atr3.py", line 22, in <module>
    import gevent  # pip install gevent
ImportError: No module named gevent

But it works in parrot linux perfectly - even though module gevent is install in kali linux.. it comes back with error

**Comment by p0isonBR** [comment]
Run: $ pip install gevent
for solve any problems, during install (in my case, an error occurred related PEP517), in this case, run $ pip2 install gevent

**Comment by filebe777** [comment]
i fixed it
sudo apt-get install gevent hen install some other things ..it work fine in kali now
